version: '3.8'

services:
  postgres:
    image: postgres:15
    volumes:
      - postgres_keycloak_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password
    networks:
      - keycloak_network

  keycloak:
    image: quay.io/keycloak/keycloak:24.0.1
    container_name: scan3d-keycloak
    command: start-dev
    environment:
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres:5432/keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: password
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - "8081:8080"
    depends_on:
      - postgres
    networks:
      - keycloak_network


  # Database cho Scan3D App
  scan3d-db:
    image: postgres:15
    container_name: scan3d-postgres
    volumes:
      - postgres_scan3d_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: scan3d-db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    networks:
      - keycloak_network

networks:
  keycloak_network:
    driver: bridge

volumes:
  postgres_keycloak_data:
  postgres_scan3d_data:
